### ISSUE TITLE
`Markdown` module conflicts with `RedcarpetCompat`

### ISSUE THREAD

**Issue by dongli** [rosschapman/markdownjs-rails#1]
In my app, I used `Redcarpet` to process `markdown` content, but now I would like to use `Markdown.js` to do the job on the browser. When I added `markdownjs-rails` gem and started the server, I encountered the error:

```
markdownjs-rails-1.0.1/lib/markdownjs-rails.rb:1:in `<top (required)>': Markdown is not a module (TypeError)
```

I checked the `Markdown` entity, and it is `RedcarpetCompat`, so there is name conflicts. How to solve this problem? Rename `Markdown` module? Thanks in advance!

**Comment by dongli** [comment]
I have removed `Redcarpet` entirely!

**Comment by rosschapman** [comment]
@dongli at long last I will respond. Deepest apologies for not resolving this sooner. The latest version of the gem should be namespaced properly by https://github.com/rosschapman/markdownjs-rails/commit/cabae3a519b6b19eb6862c4bbc9218a67fa57a2c#commitcomment-17308225. Happy coding.
